[project]
name = "loesung"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "uli.winkler", email = "uli.winkler@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "python-multipart",
    "httpx",
]

[dependency-groups]
dev = ["pytest"]

[project.scripts]
loesung = "loesung:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
